const lower=s=>(s||'').toLowerCase();
const vocab={
 business:['negócio','cliente','comprador','mercado','produto','serviço','preço','empresa','empreender','saas','vender','receita'],
 decision:['decidir','decisão','escolher','alternativa','opção','trade-off','risco'],
 productivity:['produtividade','planejar','executar','priorizar','prazo','tarefa','cronograma','organizar','tempo'],
 learning:['aprender','estudar','curso','estudo','ensinar','praticar','treinar','idioma','inglês'],
 project:['projeto','aplicativo','app','sistema','implementar','desenvolver','mvp','produto digital'],
 analysis:['analisar','auditar','diagnóstico','avaliar','investigar','causa','evidência','indicador'],
 writing:['escrever','texto','email','e-mail','relatório','documento','post','currículo','mensagem'],
 process:['processo','fluxo','protocolo','adesão','gargalo','melhoria','indicadores','implantação','padronização'],
 research:['pesquisar','pesquisa','evidência científica','artigo','literatura','fontes','referências']
};
export function detectIntents(text){const t=lower(text);const ranked=Object.entries(vocab).map(([intent,words])=>({intent,score:words.reduce((s,w)=>s+(t.includes(w)?(w.includes(' ')?2:1):0),0)})).sort((a,b)=>b.score-a.score);const primary=ranked[0]?.score>0?ranked[0].intent:'general';const secondary=ranked[1]?.score>0&&ranked[1].score>=Math.max(1,ranked[0].score*.5)?ranked[1].intent:null;const total=ranked.reduce((s,x)=>s+x.score,0);return{primary,secondary,confidence:total?Math.min(1,ranked[0].score/Math.max(1,total)+.35):.4,ranking:ranked};}
export function suggestStrategy(primary,secondary=null){const map={business:'Dor → usuário → comprador → solução → proposta de valor → viabilidade → teste',decision:'Alternativas → critérios → pesos → riscos → reversibilidade → decisão',productivity:'Objetivo → entregáveis → etapas → prioridade → prazo → próxima ação',learning:'Nível atual → objetivo → lacunas → prática → revisão → medição',project:'Problema → usuário → requisitos → MVP → riscos → métricas → execução',analysis:'Problema → evidências → causas → hipóteses → opções → recomendação',writing:'Objetivo → público → mensagem → tom → estrutura → revisão',process:'Processo atual → gargalos → causas → riscos → intervenção → indicadores → monitoramento',research:'Pergunta → escopo → fontes → evidências → síntese → limitações → conclusão',general:'Objetivo → contexto → regras → formato → critérios → execução'};return{name:secondary&&secondary!==primary?`${map[primary]||map.general} + elementos de ${map[secondary]||secondary}`:(map[primary]||map.general)};}
export function analyzePrompt(text){const clean=(text||'').trim();const sections={objective:/(objetivo|meta|resultado|quero|preciso|crie|analise)/i.test(clean),context:/(contexto|cenário|situação|dados|histórico|informações)/i.test(clean),constraints:/(restri|não |obrigatório|deve |limite|considere)/i.test(clean),format:/(formato|tabela|lista|passo|json|documento|resumo|relatório|checklist|plano)/i.test(clean),success:/(critério|sucesso|qualidade|mensur|validar|avalia)/i.test(clean),audience:/(público|usuário|leitor|equipe|cliente|aluno|paciente)/i.test(clean)};const issues=[],recommendations=[];if(!sections.objective){issues.push({code:'ambiguous_objective',title:'Objetivo pouco explícito',message:'O resultado esperado não está suficientemente claro.'});recommendations.push('Declare o objetivo com um verbo de ação e um resultado observável.');}if(!sections.context&&clean.length<220){issues.push({code:'insufficient_context',title:'Contexto insuficiente',message:'Faltam informações para orientar uma resposta consistente.'});recommendations.push('Inclua cenário, dados, histórico e limitações relevantes.');}if(!sections.constraints){issues.push({code:'missing_constraints',title:'Regras e limites pouco definidos',message:'O modelo pode tomar decisões que você não pretendia.'});recommendations.push('Declare o que deve, pode e não pode ser feito.');}if(!sections.format){issues.push({code:'missing_output_format',title:'Formato de saída indefinido',message:'A resposta pode vir em estrutura pouco útil.'});recommendations.push('Informe o formato final esperado.');}if(!sections.success){issues.push({code:'missing_success_criteria',title:'Critérios de sucesso ausentes',message:'Não há referência clara para avaliar a resposta.'});recommendations.push('Adicione critérios de qualidade ou condições de conclusão.');}if(!sections.audience)recommendations.push('Quando relevante, informe quem utilizará ou receberá o resultado.');if(clean.split(/\s+/).filter(Boolean).length>800){issues.push({code:'possible_overload',title:'Possível excesso de conteúdo',message:'O prompt pode estar carregado demais.'});recommendations.push('Separe contexto essencial de detalhes secundários.');}return{issues,recommendations,sections};}
export function buildOptimizedPrompt(data={}){const intents=data.intents||detectIntents(`${data.objective||''} ${data.context||''}`);const strategy=data.strategy||suggestStrategy(intents.primary,intents.secondary);const b=[];if(data.objective)b.push(`OBJETIVO\n${data.objective.trim()}`);if(data.context)b.push(`CONTEXTO\n${data.context.trim()}`);if(data.audience)b.push(`PÚBLICO / USUÁRIO\n${data.audience.trim()}`);b.push(`ESTRATÉGIA DE RACIOCÍNIO\nUse a estrutura: ${strategy.name}.`);if(data.constraints)b.push(`REGRAS E RESTRIÇÕES\n${data.constraints.trim()}`);if(data.format)b.push(`FORMATO DE SAÍDA\nEntregue o resultado em: ${data.format.trim()}.`);if(data.success)b.push(`CRITÉRIOS DE SUCESSO\n${data.success.trim()}`);if(data.examples)b.push(`EXEMPLOS / REFERÊNCIAS\n${data.examples.trim()}`);if(data.style)b.push(`TOM E ESTILO\n${data.style.trim()}`);b.push('EXECUÇÃO\n1. Verifique se as informações são suficientes.\n2. Diferencie fatos, hipóteses e recomendações.\n3. Sinalize lacunas críticas em vez de inventar dados.\n4. Priorize clareza, aplicabilidade e consistência.\n5. Revise o resultado usando os critérios de sucesso antes de finalizar.');return b.join('\n\n');}
export function doctorPrompt(text){const beforeAnalysis=analyzePrompt(text);const beforeScore=scoreLocal(text,beforeAnalysis);const intents=detectIntents(text);const strategy=suggestStrategy(intents.primary,intents.secondary);const changes=[];if(beforeAnalysis.issues.some(i=>i.code==='ambiguous_objective'))changes.push('Tornei o objetivo explícito.');if(beforeAnalysis.issues.some(i=>i.code==='insufficient_context'))changes.push('Adicionei orientação para explicitar contexto e lacunas.');if(beforeAnalysis.issues.some(i=>i.code==='missing_constraints'))changes.push('Incluí regras de execução e proteção contra suposições.');if(beforeAnalysis.issues.some(i=>i.code==='missing_output_format'))changes.push('Adicionei exigência de estrutura executável.');if(beforeAnalysis.issues.some(i=>i.code==='missing_success_criteria'))changes.push('Adicionei critérios de revisão.');const improved=`OBJETIVO\nExecute o pedido abaixo preservando sua intenção principal:\n${text}\n\nESTRATÉGIA\n${strategy.name}.\n\nREGRAS\n- Não invente informações ausentes.\n- Diferencie fatos, hipóteses e recomendações.\n- Se faltar informação crítica, sinalize a lacuna.\n- Evite repetição e conteúdo sem função.\n\nFORMATO\nOrganize a resposta para uso direto, com etapas, decisões ou seções conforme a natureza do pedido.\n\nCRITÉRIOS DE QUALIDADE\n- Clareza.\n- Aplicabilidade.\n- Coerência com o objetivo.\n- Premissas explícitas.\n- Próximos passos identificáveis.\n\nREVISÃO FINAL\nVerifique se a resposta realmente resolve o pedido e se algo importante ficou de fora.`;const afterAnalysis=analyzePrompt(improved);const afterScore=scoreLocal(improved,afterAnalysis);return{intents,changes:changes.length?changes:['Reestruturei o prompt para aumentar clareza, controle e verificabilidade.'],before:{text,analysis:beforeAnalysis,score:beforeScore},after:{text:improved,analysis:afterAnalysis,score:afterScore}};}
function scoreLocal(text,analysis){const s=analysis.sections;const d={Clareza:s.objective?88:45,Contexto:s.context||text.length>220?82:48,Controle:s.constraints?88:50,Estrutura:s.format?90:48,Verificabilidade:s.success?90:45,Direcionamento:s.audience?86:68};return{overall:Math.round(Object.values(d).reduce((a,b)=>a+b,0)/Object.keys(d).length),dimensions:d};}
